export const routes = {
  Dashboards: {
    Default: '/crmAdmin',
    Manager: '/crmManager',
    ECommerce: '/dashboards/dashboard_ecommerce',
    Project: '/dashboards/dashboard_project',
    NoAccess: '/no-access',
  },
  CrmAdmin: {
    Dashboard: '/crmAdmin',
    Companies: '/crmAdmin/companies',
    Contacts: '/crmAdmin/contacts',
    Deals: '/crmAdmin/deals',
    Projects: '/crmAdmin/Projects',
    ProjectDetails: '/crmAdmin/Projects/details',
    ProjectList: '/crmAdmin/Projects/list',
    Tasks: '/crmAdmin/task',
    Report: '/crmAdmin/Report',
    Users: '/crmAdmin/users',
    UserList: '/crmAdmin/users/list',
    Roles: '/crmAdmin/roles',
    Settings: '/crmAdmin/settings',
  },
  Master: {
    Root: '/crmAdmin/master',
    Jabatan: '/crmAdmin/master/jabatan',
    Cabang: '/crmAdmin/master/cabang',
    Devisi: '/crmAdmin/master/devisi',
    TipeMarketing: '/crmAdmin/master/tipe-marketing',
  },
  Widgets: {
    General: '/widgets/general',
    Charts: '/widgets/Chart',
  },
  Project: {
    ProjectDetails: '/crmAdmin/Projects/details',
    ProjectList: '/crmAdmin/Projects/list',
    ProjectCreate: '/project/project_create',
  },
  App: {
    FileManager: '/app/file_manager',
    KanbanBoard: '/crmAdmin/deals',
    MailBox: '/app/mail_box',
    BookMarks: '/app/bookmark',
    Contacts: '/crmAdmin/contacts',
    RumahSakit: '/crmAdmin/companies',
    Task: '/crmAdmin/task',
    Calender: '/app/calender',
    SocialApps: '/app/social_app',
    Todo: '/app/todo',
    SearchResult: '/app/serach_result',
    Buttons: '/app/buttons',
  },
  Ecommerce: {
    Products: {
      AddProduct: '/product/addProduct',
      ProductGrid: '/product/grid',
      ProductList: '/product/list',
      ProductDetails: '/product/details/:id',
    },
    Seller: {
      SellerList: '/seller/list',
      SellerDetails: '/seller/details/:id',
    },
    Orders: {
      OrderHistory: '/order/history',
      OrderDetails: '/order/details/:orderNumber',
    },
    Invoice: {
      Invoice1: '/ecommerce/invoice_1',
      Invoice2: '/ecommerce/invoice_2',
      Invoice3: '/ecommerce/invoice_3',
      Invoice4: '/ecommerce/invoice_4',
      Invoice5: '/ecommerce/invoice_5',
      Invoice6: '/ecommerce/invoice_6',
    },
    Category: '/ecommerce/category',
    Cart: '/ecommerce/cart',
    Wishlist: '/ecommerce/wishlist',
    Checkout: '/ecommerce/checkout',
  },
  Chat: {
    PrivateChat: '/chat/private-chat',
    GroupChat: '/chat/group-chat',
  },
  User: {
    UserProfile: '/user/user-profile',
    AkunSaya: '/akun-saya',
    AddUser: '/user/add-user',
    UserList: '/crmAdmin/users/list',
    UserCards: '/user/user-cards',
    Roles: '/crmAdmin/roles',
    UserHierarchy: '/crmAdmin/users/hierarchy',
  },
  Reports: {
    Product: '/reports/products',
    Sales: '/reports/sales',
    SalesReturn: '/reports/sales_return',
    CustomerOrder: '/reports/customer_order',
  },
  Forms: {
    FormControls: {
      FormValidation: '/forms/form_control/form_validation',
      BaseInput: '/forms/form_control/base_input',
      CheckboxRadio: '/forms/form_control/checkbox_radio',
      InputGroups: '/forms/form_control/input_groups',
      InputMask: '/forms/form_control/input_mask',
      MegaOptions: '/forms/form_control/mega_options',
    },
    FormWidgets: {
      Datepicker: '/forms/form_widgets/datepicker',
      TouchSpin: '/forms/form_widgets/touchSpin',
      Select2: '/forms/form_widgets/select2',
      Switch: '/forms/form_widgets/switch',
      Typeahead: '/forms/form_widgets/type-ahead',
      Clipboard: '/forms/form_widgets/clipboard',
    },
    FormLayout: {
      FormWizard1: '/forms/form_layout/form_wizard',
      FormWizard2: '/forms/form_layout/form_wizard_two',
      TwoFactor: '/forms/form_layout/two_factor',
    },
  },
  Table: {
    BootstrapTables: {
      BasicTables: '/table/bootstrap_tables/basic_tables',
      TableComponents: '/table/bootstrap_tables/table_components',
    },
    DataTable: '/table/data_table',
  },
  UiKits: {
    Typography: '/uikits/typography',
    Avatars: '/uikits/avatars',
    Divider: '/uikits/divider',
    HelperClasses: '/uikits/helper_classes',
    Grid: '/uikits/grid',
    TagPills: '/uikits/tag_pills',
    Progress: '/uikits/progress',
    Modal: '/uikits/modal',
    Alert: '/uikits/alert',
    Popover: '/uikits/popover',
    Placeholders: '/uikits/placeholders',
    Tooltip: '/uikits/tooltip',
    Dropdown: '/uikits/dropdown',
    Accordion: '/uikits/accordion',
    Tabs: '/uikits/tabs',
    Offcanvas: '/uikits/offcanvas',
    NavigateLinks: '/uikits/navigatelinks',
    Lists: '/uikits/lists',
  },
  BonusUI: {
    Scrollable: '/bonus_ui/scrollable',
    TreeView: '/bonus_ui/tree',
    Toast: '/bonus_ui/toast',
    BlockUI: '/bonus_ui/block_ui',
    Rating: '/bonus_ui/rating',
    Dropzone: '/bonus_ui/dropzone',
    Tour: '/bonus_ui/tour',
    SweetAlert2: '/bonus_ui/sweetalert2',
    AnimatedModal: '/bonus_ui/animated_modal',
    Swiper: '/bonus_ui/swiper',
    Ribbons: '/bonus_ui/ribbons',
    Pagination: '/bonus_ui/pagination',
    ScrollSpy: '/bonus_ui/scrollspy',
    Breadcrumb: '/bonus_ui/breadcrumb',
    RangeSlider: '/bonus_ui/range_slider',
    Ratios: '/bonus_ui/ratios',
    ImageCropper: '/bonus_ui/image_cropper',
    BasicCard: '/bonus_ui/basic_card',
    CreativeCard: '/bonus_ui/creative_card',
    DraggableCard: '/bonus_ui/draggable_card',
    Timeline: '/bonus_ui/timeline',
  },
  Animations: {
    Animate: '/animation/animate',
    Aos: '/animation/aos',
  },
  Icons: {
    FlagIcon: '/icon/flag_icon',
    FontAwesomeIcon: '/icon/font_awesome_icon',
    IcoIcon: '/icon/ico_icon',
    ThemifyIcon: '/icon/thimify_icon',
    FeatherIcon: '/icon/feather_icon',
    WeatherIcon: '/icon/weather_icon',
  },
  Charts: {
    ApexChart: '/charts/apex_chart',
    GoogleChart: '/charts/google_chart',
    ChartistChart: '/charts/chartist',
    ChartJsChart: '/charts/chart_js',
  },
  Pages: {
    SamplePage: '/pages/sample_Page',
    Faq: '/pages/faq',
    Pricing: '/pages/pricing',
    KnowledgeBase: '/pages/knowledgeBase',
    SupportTicket: '/pages/Support',
  },
  ErrorPages: {
    Error400: '/error/400',
    Error401: '/error/401',
    Error403: '/error/403',
    Error404: '/error/404',
    Error500: '/error/500',
    Error503: '/error/503',
  },
  Auth: {
    LoginSimple: '/auth/login_simple',
    LoginBgImage: '/auth/login_bg_image',
    LoginBgImageTwo: '/auth/login_bg_image_two',
    LoginValidation: '/auth/login_validation',
    LoginTooltip: '/auth/login_tooltip',
    LoginSweetAlert: '/auth/login_sweet_alert',
    RegisterSimple: '/auth/register',
    RegisterBgImage: '/auth/register_bg_image',
    RegisterBgImageTwo: '/auth/register_bg_image_two',
    RegisterWizard: '/auth/register_wizard',
    AccountRestricted: '/auth/account_restricted',
    UnlockUser: '/auth/unlock_user',
    ForgotPassword: '/auth/forgot_password',
    ResetPassword: '/auth/reset_password',
    Maintenance: '/auth/maintenance',
  },
  ComingSoon: {
    ComingSimple: '/coming_soon/simple',
    ComingBgVideo: '/coming_soon/coming_soon_video',
    ComingBgImage: '/coming_soon/coming_soon_image',
  },
  Gallery: {
    GalleryGrid: '/gallery/gallery_grid',
    GalleryGridDescription: '/gallery/gallery_grid_desc',
    MasonryGallery: '/gallery/masonry_gallery',
    MasonryWithDescription: '/gallery/masonry_with_desc',
    HoverEffects: '/gallery/hover_effects',
    GalleryPlaceholder: '/gallery/gallery_placeholder',
  },
  Blog: {
    Blog: '/blog/blog',
    BlogDetails: '/blog/blog_details',
    AddBlog: '/blog/add_blog',
  },
  JobSearch: {
    CardView: '/job_search/cards_view',
    ListView: '/job_search/list_view',
    JobDetails: '/job_search/job_details',
    Apply: '/job_search/apply',
  },
  Courses: {
    CourseList: '/courses/courses_list',
    CourseDetails: '/courses/courses_details',
  },
  Editors: {
    CkEditor: '/editors/ck_editors',
    MdeEditor: '/editors/mde_editors',
  },
  Maps: {
    GoogleMap: '/maps/map_google',
    LeafletMap: '/maps/leaflet_map',
  },
}
