export const routes = {
  Pages: {
    SamplePage: "/pages/sample_page",
    SamplePages1: "/pages/sample_page_1",
    SamplePages2: "/pages/sample_page_2",
  },
  Dashboards: {
    Default: '/dashboards/dashboard_default',
    Ecommerce: '/dashboards/dashboard_ecommerce',
    Project: '/dashboards/dashboard_project',
  },
  Project: {
    ProjectDetails: '/project/project_details',
    ProjectList: '/project/project_list',
    ProjectCreate: '/project/project_create',
  },
  App: {
    KanbanBoard: '/app/kanban_board',
    Contacts: '/app/contacts',
    Hospital: '/app/hospital',
    Task: '/app/task',
  },
  User: {
    UserProfile: '/user/user-profile',
    AddUser: '/user/add-user',
    UserList: '/user/user-list',
    UserCards: '/user/user-cards',
    Roles: '/user/roles-permission',
  },
  Auth: {
    LoginSimple: '/auth/login_simple',
    LoginBgImage: '/auth/login_bg_image',
    LoginBgImageTwo: '/auth/login_bg_image_two',
    LoginValidation: '/auth/login_validation',
    LoginTooltip: '/auth/login_tooltip',
    LoginSweetAlert: '/auth/login_sweet_alert',
    RegisterSimple: '/auth/register',
    RegisterBgImage: '/auth/register_bg_image',
    RegisterBgImageTwo: '/auth/register_bg_image_two',
    RegisterWizard: '/auth/register_wizard',
    AccountRestricted: '/auth/account_restricted',
    UnlockUser: '/auth/unlock_user',
    ForgotPassword: '/auth/forgot_password',
    ResetPassword: '/auth/reset_password',
    Maintenance: '/auth/maintenance',
  },
};
